# Generated by Django 4.2.17 on 2025-01-28 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پرونده')),
                ('description', models.TextField(verbose_name='شرح پرونده')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس پرونده')),
                ('location', models.CharField(max_length=200, verbose_name='محل وقوع')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پرونده')),
                ('report', models.TextField(verbose_name='گزارش پلیس')),
                ('Video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ویدیو پرونده')),
                ('result', models.TextField(verbose_name='دادنامه پرونده')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('age_range', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=5, verbose_name='رده سنی')),
                ('difficulty_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='درجه سختی')),
                ('difficulty_level', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=20, verbose_name='سطح سختی')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.casecategory', verbose_name='دسته\u200cبندی پرونده')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس مظنون')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ویدیو بازجویی')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(choices=[('murderer', 'قاتل'), ('murdered', 'مقتول'), ('innocent', 'بی گناه')], default='innocent', max_length=10, verbose_name='نقش')),
                ('job', models.CharField(blank=True, max_length=200, null=True, verbose_name='َشغل')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('height', models.FloatField(verbose_name='قد (سانتی\u200cمتر)')),
                ('weight', models.FloatField(verbose_name='وزن (کیلوگرم)')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='گروه خونی')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متاهل'), ('divorced', 'طلاق گرفته')], max_length=20, verbose_name='وضعیت تاهل')),
                ('relationship_with_victim', models.CharField(blank=True, max_length=200, null=True, verbose_name='ارتباط با مقتول')),
                ('excuse', models.TextField(blank=True, null=True, verbose_name='بهانه مظنون')),
                ('last_seen', models.TextField(blank=True, null=True, verbose_name='آخرین بازدید')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect', to='Product.case')),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='ضربان قلب (بیت در دقیقه)')),
                ('face_expression', models.CharField(choices=[('neutral', 'خنثی'), ('happy', 'خوشحال'), ('angry', 'عصبانی'), ('sad', 'غمگین'), ('surprised', 'متعجب'), ('fearful', 'ترسیده'), ('nervous', 'نگران')], max_length=50, verbose_name='حالت چهره')),
                ('truth_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='میزان حقیقت ادعاهای مظنون در بازجویی (1 = دروغ، 10 = حقیقت)', verbose_name='میزان حقیقت (1 تا 10)')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='Product.suspect', verbose_name='مظنون')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('VOICE', 'Voice'), ('AUTOPSY', 'Autopsy'), ('OTHER', 'Other')], max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک')),
                ('description', models.TextField(verbose_name='توضیحات مدرک')),
                ('details', models.TextField(blank=True, null=True, verbose_name='جزییات مدرک')),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidences/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس مدرک')),
                ('status', models.CharField(choices=[('Locked', 'locked'), ('Unlocked', 'Unlocked')], default='Unlocked', max_length=20)),
                ('password', models.CharField(blank=True, help_text='فقط برای مدارکی که قفل هستند استفاده می\u200cشود.', max_length=128, null=True, verbose_name='رمز عبور')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='Product.case')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='Product.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
