# Generated by Django 4.2.17 on 2024-12-28 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پرونده')),
                ('description', models.TextField(verbose_name='شرح پرونده')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس پرونده')),
                ('location', models.CharField(max_length=200, verbose_name='محل وقوع')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پرونده')),
                ('report', models.TextField(verbose_name='گزارش پلیس')),
                ('Video', models.FileField(upload_to='videos/', verbose_name='ویدیو پرونده')),
                ('result', models.TextField(verbose_name='دادنامه پرونده')),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='فعال')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('age_range', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=5, verbose_name='رده سنی')),
                ('difficulty_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='درجه سختی')),
                ('difficulty_level', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=20, verbose_name='سطح سختی')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دسته\u200cبندی')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('height', models.FloatField(verbose_name='قد (سانتی\u200cمتر)')),
                ('weight', models.FloatField(verbose_name='وزن (کیلوگرم)')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='گروه خونی')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متاهل'), ('divorced', 'طلاقت گرفته')], max_length=20, verbose_name='وضعیت تاهل')),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='ضربان قلب (بیت در دقیقه)')),
                ('face_expression', models.CharField(choices=[('neutral', 'خنثی'), ('happy', 'خوشحال'), ('angry', 'عصبانی'), ('sad', 'غمگین'), ('surprised', 'متعجب'), ('fearful', 'ترسیده'), ('nervous', 'نگران')], max_length=50, verbose_name='حالت چهره')),
                ('truth_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='میزان حقیقت ادعاهای مظنون در بازجویی (1 = دروغ، 10 = حقیقت)', verbose_name='میزان حقیقت (1 تا 10)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='Product.case', verbose_name='پرونده')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='Product.suspect', verbose_name='مظنون')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('Voice', 'Voice'), ('OTHER', 'Other')], max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک')),
                ('description', models.TextField()),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidences/')),
                ('status', models.CharField(choices=[('Locked', 'Unlocked'), ('Locked', 'Unlocked')], default='Unlocked', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='Product.case')),
                ('suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='Product.suspect')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category', verbose_name='دسته\u200cبندی پرونده'),
        ),
    ]
