# Generated by Django 4.2.17 on 2024-12-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='alibi',
            field=models.TextField(blank=True, null=True, verbose_name='بهانه یا توضیحات مظنون'),
        ),
        migrations.AddField(
            model_name='suspect',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='َشغل'),
        ),
        migrations.AddField(
            model_name='suspect',
            name='murderer',
            field=models.BooleanField(default=False, verbose_name='قاتل'),
        ),
        migrations.AddField(
            model_name='suspect',
            name='relationship_with_victim',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ارتباط با مقتول'),
        ),
        migrations.AlterField(
            model_name='case',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال'),
        ),
    ]
