# Generated by Django 4.2.17 on 2024-12-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_suspect_alibi_suspect_job_suspect_murderer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='password',
            field=models.CharField(blank=True, help_text='فقط برای مدارکی که قفل هستند استفاده می\u200cشود.', max_length=128, null=True, verbose_name='رمز عبور'),
        ),
    ]
