# Generated by Django 4.2.17 on 2024-12-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_case_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ویدیو پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز'),
        ),
    ]
