# Generated by Django 4.2.17 on 2024-12-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_case_video_alter_case_image_alter_case_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('VOICE', 'Voice'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('Locked', 'locked'), ('Unlocked', 'Unlocked')], default='Unlocked', max_length=20),
        ),
    ]
