# Generated by Django 4.2.17 on 2024-12-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_evidence_evidence_type_alter_evidence_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspect',
            old_name='alibi',
            new_name='excuse',
        ),
        migrations.AddField(
            model_name='suspect',
            name='last_seen',
            field=models.TextField(blank=True, null=True, verbose_name='بهانه یا توضیحات مظنون'),
        ),
    ]
