# Generated by Django 4.2.17 on 2024-12-30 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_rename_alibi_suspect_excuse_suspect_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suspect', to='Product.case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suspect',
            name='excuse',
            field=models.TextField(blank=True, null=True, verbose_name='بهانه مظنون'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='last_seen',
            field=models.TextField(blank=True, null=True, verbose_name='آخرین بازدید'),
        ),
    ]
