# Generated by Django 4.2.17 on 2024-12-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_suspect_case_alter_suspect_excuse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس مظنون'),
        ),
    ]
