# Generated by Django 4.2.17 on 2024-12-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_suspect_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interrogation',
            name='case',
        ),
    ]
