# Generated by Django 4.2.17 on 2025-01-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی پرونده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دسته\u200cبندی پرونده')),
            ],
        ),
    ]
