# Generated by Django 4.2.17 on 2025-01-29 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdeviceinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
